baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

enableEmoji = true

# Theme Settings
theme = "relearn"

[params]
  collapsibleMenu = true
  showVisitedLinks = true
  themeVariant='my-custom-variant'
