baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

enableEmoji = true

# Theme Settings
theme = "relearn"
[params]
  collapsibleMenu = true
  showVisitedLinks = true
  
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
