baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
# Theme Settings
theme = "tale"
[params]
  Author = "Doug M" # Add the name of the author (this theme only supports one author)
[author]
  name = "EmbeddedUniversity" # Used by the foot copyright
